= HTTP

The HTTP module contains a simple HTTP server, which can be started locally to stub an HTTP service.


== Create and Start the Stub

Instantiating the link:{javadoc-url}/http/org/stubit/http/HttpStub.html[`HttpStub` class] automatically starts the stub at a random local port.

[source,java,indent=0]
----
include::../../../test/java/org/stubit/http/HttpDocTest.java[tag=create]
----

You can get its address via the link:{javadoc-url}/http/org/stubit/http/HttpStub.html#address()[`address` method]

[source,java,indent=0]
----
include::../../../test/java/org/stubit/http/HttpDocTest.java[tag=address]
----


== Unstubbed Behaviour

By default, the stub will return a 404 response for any path and any method but POST.

[source,java,indent=0]
----
include::../../../test/java/org/stubit/http/HttpDocTest.java[tag=get-unstubbed]
----


=== POST Requests

POST requests will by default return a 201 response for any path.

[source,java,indent=0]
----
include::../../../test/java/org/stubit/http/HttpDocTest.java[tag=post-unstubbed]
----

The body of the request will be returned for subsequent GET requests.

[source,java,indent=0]
----
include::../../../test/java/org/stubit/http/HttpDocTest.java[tag=get-posted]
----

NOTE: This behaviour is likely to change in future releases!


== Stub a Response

You can create a stubbing via the link:{javadoc-url}/http/org/stubit/http/Stubbing.html#stub()[`Stubbing.stub()` method]

[source,java,indent=0]
----
include::../../../test/java/org/stubit/http/HttpDocTest.java[tag=create-stubbing]
----
<1> Specifies the path for the stubbing.
<2> Specifies the method.
<3> Specifies the response that will be returned.

The link:{javadoc-url}/http/org/stubit/http/Stubbing.html[`Stubbing`] then needs to be added via the link:{javadoc-url}/http/org/stubit/http/HttpStub.html#add(org.stubit.http.Stubbing...)[`add` method]

[source,java,indent=0]
----
include::../../../test/java/org/stubit/http/HttpDocTest.java[tag=add-stubbing]
----

Further requests matching the link:{javadoc-url}/http/org/stubit/http/Stubbing.html[`Stubbing`] will now return the link:{javadoc-url}/http/org/stubit/http/StubbedRequest.html[`StubbedRequest`] instead of the default response.

[source,java,indent=0]
----
include::../../../test/java/org/stubit/http/HttpDocTest.java[tag=request-stubbing]
----
