= Random

The Random module contains a collection of builders and utility functions to generate random data.


== Random Integer

The link:{javadoc-url}/http/org/stubit/random/RandomInt.html[`RandomInt` class] allows to generate random Integer values within a defined min and max range (both inclusive).

For simple integers there are several static methods available.
More complex integers can be defined with a Builder class that's returned by the `andInt` method.

NOTE:: It is not possible to set max to Integer.MAX_VALUE.
The maximum value is Integer.MAX_VALUE - 1.
This is due to the fact that the SecureRandom.nextInt(int) method is exclusive of the upper bound.


=== Between Min and Max

[source,java,indent=0]
----
include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=anIntBetween]
----


=== Positive Integer

[source,java,indent=0]
----
include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=aPositiveInt]
----


=== Negative Integer

[source,java,indent=0]
----
include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=aNegativeInt]
----


=== Builder

[source,java,indent=0]
----
include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=anInt]
----


== Random Choice

The link:{javadoc-url}/http/org/stubit/random/RandomChoice.html[`RandomChoice` class] allows to make a random choice from the objects in a Collection, an Array, or the values of an Enum type.

For simple selections there are several static `chooseAnyFrom` methods available.
More complex selections can be defined with a Builder class that's returned by the `from` method.


=== From Collection

[source,java,indent=0]
----
include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=anyOf_list]

include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=anyOf_map]
----


=== From Array

[source,java,indent=0]
----
include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=anyOf_ellipsis]

include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=anyOf_array]
----


=== From Enum Type

[source,java,indent=0]
----
include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=any_enum]
----

=== Builder

[source,java,indent=0]
----
include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=aChoiceFrom_ellipsis]

include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=aChoiceFrom_array]

include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=aChoiceFrom_list]
include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=aChoiceFrom_map]

include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=aChoiceFromValuesOf_enum]
----


==== Additional Choices

[source,java,indent=0]
----
include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=and]
----


==== Excluding Choices

[source,java,indent=0]
----
include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=butNot]
----
