= Random

The Random module contains a collection of builders and utility functions to generate random data.


== Random Integer/Long

The link:{javadoc-url}/random/org/stubit/random/RandomInt.html[`RandomInt`] and link:{javadoc-url}/random/org/stubit/random/RandomLong.html[`RandomLong`] classes allow to generate random Integer/Long values within a defined min and max range (both inclusive).

For simple integers/longs there are several static methods available.
More complex integers/long can be defined with Builder classes that's returned by the `anInt`/`aLong` methods.

NOTE:: It is not possible to set max to `Integer.MAX_VALUE` or `Long.MAX_VALUE`.
The maximum values are `Integer.MAX_VALUE - 1` and `Long.MAX_VALUE - 1`.
This is due to the fact that the `SecureRandom.nextInt(int)` and `SecureRandom.nextLong(long)` methods are exclusive of the upper bound.


=== Between Min and Max

[source,java,indent=0]
----
include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=anIntBetween]

include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=aLongBetween]
----


=== Positive Integer/Long

[source,java,indent=0]
----
include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=aPositiveInt]
----

[source,java,indent=0]
----
include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=aPositiveLong]
----


=== Negative Integer/Long

[source,java,indent=0]
----
include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=aNegativeInt]
----

[source,java,indent=0]
----
include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=aNegativeLong]
----


=== Builder

[source,java,indent=0]
----
include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=anInt]
----

[source,java,indent=0]
----
include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=aLong]
----


== Random Choice

The link:{javadoc-url}/random/org/stubit/random/RandomChoice.html[`RandomChoice` class] allows to make a random choice from the objects in a Collection, an Array, or the values of an Enum type.

For simple selections there are several static `chooseAnyFrom` methods available.
More complex selections can be defined with a Builder class that's returned by the `from` method.


=== From Collection

[source,java,indent=0]
----
include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=anyOf_list]

include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=anyOf_map]
----


=== From Array

[source,java,indent=0]
----
include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=anyOf_ellipsis]

include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=anyOf_array]
----


=== From Enum Type

[source,java,indent=0]
----
include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=any_enum]
----

=== Builder

[source,java,indent=0]
----
include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=aChoiceFrom_ellipsis]

include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=aChoiceFrom_array]

include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=aChoiceFrom_list]
include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=aChoiceFrom_map]

include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=aChoiceFromValuesOf_enum]
----


==== Additional Choices

[source,java,indent=0]
----
include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=and]
----


==== Excluding Choices

[source,java,indent=0]
----
include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=butNot]
----


== Random String

The link:{javadoc-url}/random/org/stubit/random/RandomString.html[`RandomString` class] allows to generate random Strings.

[source,java,indent=0]
.Random German licence plate
----
include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=germanLicensePlate]
----

[source,java,indent=0]
.Random Iranian licence plate
----
include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=iranianLicensePlate]
----


== Random Duration

The link:{javadoc-url}/random/org/stubit/random/RandomDuration.html[`RandomDuration` class] allows to generate random Durations.

[source,java,indent=0]
----
include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=aDurationBetween]
----

[source,java,indent=0]
----
include::../../../test/java/org/stubit/random/RandomDocTest.java[tag=aDuration]
----
