= Random

The Random module contains a collection of builders and utility functions to generate random data.


== Random Number

The link:{javadoc-url}/random/org/stubit/random/RandomNumber.html[`RandomNumber`] class allows to generate random Integer/Long values within a defined min and max range (both inclusive).

For simple integers/longs there are several static methods available.
More complex integers/long can be defined with Builder classes that's returned by the `anInt`/`aLong` methods.

NOTE:: It is not possible to set max to `Integer.MAX_VALUE` or `Long.MAX_VALUE`.
The maximum values are `Integer.MAX_VALUE - 1` and `Long.MAX_VALUE - 1`.
This is due to the fact that the `SecureRandom.nextInt(int)` and `SecureRandom.nextLong(long)` methods are exclusive of the upper bound.


=== Between Min and Max

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/RandomDocTest.java[tag=anIntBetween]

include::../../../test/java/examples/java/RandomDocTest.java[tag=aLongBetween]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/RandomDocTest.kt[tag=anIntBetween]

include::../../../test/kotlin/examples/kotlin/RandomDocTest.kt[tag=aLongBetween]
----


=== Positive Integer/Long

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/RandomDocTest.java[tag=aPositiveInt]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/RandomDocTest.kt[tag=aPositiveInt]
----

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/RandomDocTest.java[tag=aPositiveLong]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/RandomDocTest.kt[tag=aPositiveLong]
----


=== Negative Integer/Long

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/RandomDocTest.java[tag=aNegativeInt]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/RandomDocTest.kt[tag=aNegativeInt]
----

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/RandomDocTest.java[tag=aNegativeLong]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/RandomDocTest.kt[tag=aNegativeLong]
----


=== Builder

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/RandomDocTest.java[tag=anInt]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/RandomDocTest.kt[tag=anInt]
----

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/RandomDocTest.java[tag=aLong]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/RandomDocTest.kt[tag=aLong]
----


== Random Choice

The link:{javadoc-url}/random/org/stubit/random/RandomChoice.html[`RandomChoice` class] allows to make a random choice from the objects in a Collection, an Array, or the values of an Enum type.

For simple selections there are several static `chooseAnyFrom` methods available.
More complex selections can be defined with a Builder class that's returned by the `from` method.


=== From Collection

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/RandomDocTest.java[tag=anyOf_list]

include::../../../test/java/examples/java/RandomDocTest.java[tag=anyOf_map]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/RandomDocTest.kt[tag=anyOf_list]

include::../../../test/kotlin/examples/kotlin/RandomDocTest.kt[tag=anyOf_map]
----


=== From Array

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/RandomDocTest.java[tag=anyOf_ellipsis]

include::../../../test/java/examples/java/RandomDocTest.java[tag=anyOf_array]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/RandomDocTest.kt[tag=anyOf_ellipsis]

include::../../../test/kotlin/examples/kotlin/RandomDocTest.kt[tag=anyOf_array]
----


=== From Enum Type

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/RandomDocTest.java[tag=any_enum]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/RandomDocTest.kt[tag=any_enum]
----

=== Builder

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/RandomDocTest.java[tag=aChoiceFrom_ellipsis]

include::../../../test/java/examples/java/RandomDocTest.java[tag=aChoiceFrom_array]

include::../../../test/java/examples/java/RandomDocTest.java[tag=aChoiceFrom_list]
include::../../../test/java/examples/java/RandomDocTest.java[tag=aChoiceFrom_map]

include::../../../test/java/examples/java/RandomDocTest.java[tag=aChoiceFromValuesOf_enum]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/RandomDocTest.kt[tag=aChoiceFrom_ellipsis]

include::../../../test/kotlin/examples/kotlin/RandomDocTest.kt[tag=aChoiceFrom_array]

include::../../../test/kotlin/examples/kotlin/RandomDocTest.kt[tag=aChoiceFrom_list]
include::../../../test/kotlin/examples/kotlin/RandomDocTest.kt[tag=aChoiceFrom_map]

include::../../../test/kotlin/examples/kotlin/RandomDocTest.kt[tag=aChoiceFromValuesOf_enum]
----


==== Additional Choices

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/RandomDocTest.java[tag=and]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/RandomDocTest.kt[tag=and]
----


==== Excluding Choices

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/RandomDocTest.java[tag=butNot]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/RandomDocTest.kt[tag=butNot]
----


== Random String

The link:{javadoc-url}/random/org/stubit/random/RandomString.html[`RandomString` class] allows to generate random Strings.

E.g. to generate a random German licence plate:

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/RandomDocTest.java[tag=germanLicensePlate]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/RandomDocTest.kt[tag=germanLicensePlate]
----

Or an Iranian licence plate:

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/RandomDocTest.java[tag=iranianLicensePlate]
----
[source,kotlin,indent=0,role="secondary"]
.Java
----
include::../../../test/kotlin/examples/kotlin/RandomDocTest.kt[tag=iranianLicensePlate]
----


== Random Duration

The link:{javadoc-url}/random/org/stubit/random/RandomDuration.html[`RandomDuration` class] allows to generate random Durations.

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/RandomDocTest.java[tag=aDurationBetween]
----

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/RandomDocTest.java[tag=aDuration]
----

== Random Date

The link:{javadoc-url}/random/org/stubit/random/RandomLocalDate.html[`RandomLocalDate` class] allows to generate random LocalDates.

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/RandomDocTest.java[tag=aLocalDateBetween]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/RandomDocTest.kt[tag=aLocalDateBetween]
----

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/RandomDocTest.java[tag=aLocalDate]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/RandomDocTest.kt[tag=aLocalDate]
----

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/RandomDocTest.java[tag=aLocalDateInRange]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/RandomDocTest.kt[tag=aLocalDateInRange]
----

== Random Time

The link:{javadoc-url}/random/org/stubit/random/RandomLocalTime.html[`RandomLocalTime` class] allows to generate random LocalTimes.

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/RandomDocTest.java[tag=aLocalTimeBetween]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/RandomDocTest.kt[tag=aLocalTimeBetween]
----

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/RandomDocTest.java[tag=aLocalTime]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/RandomDocTest.kt[tag=aLocalTime]
----

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/RandomDocTest.java[tag=aLocalTimeInRange]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/RandomDocTest.kt[tag=aLocalTimeInRange]
----
